const date = new Date()
        const weekday = date.getDay()
        //console.log(weekday)
        const hours = date.getHours()
        //console.log(hours)
        const minutes = date.getMinutes()
        //console.log(minutes)
        let tableField = document.getElementById('table-field')

        let hétfő = document.getElementById("Hé")
        let kedd = document.getElementById("Ke")
        let szerda = document.getElementById("Sze")
        let csütörtök = document.getElementById("Csüt")
        let péntek = document.getElementById("Pén")
        let szombat = document.getElementById("Szo")
        let vasárnap = document.getElementById("Vas")

        let choirTime = document.getElementById("choir-time")
        let choirLesson = document.getElementById("choir-lesson")
        let chamber1time = document.getElementById("chamber1-time")
        let chamber1lesson = document.getElementById("chamber1-lesson")
        let guitarTime = document.getElementById("guitar-time")
        let guitarLesson = document.getElementById("guitar-lesson")
        let zirTime = document.getElementById("zir-time")
        let zirLesson = document.getElementById("zir-lesson")
        let acoTime = document.getElementById("acoustics-time")
        let acoLesson = document.getElementById("acoustics-lesson")
        let chamber2time = document.getElementById("chamber2-time")
        let chamber2lesson = document.getElementById("chamber2-lesson")
        let szolfTime = document.getElementById("szolf-time")
        let szolfLesson = document.getElementById("szolf-lesson")
        let guitarOrchTime = document.getElementById("guitarorch-time")
        let guitarOrchLesson = document.getElementById("guitarorch-lesson")
        let progTime = document.getElementById("prog-time")
        let progLesson = document.getElementById("prog-lesson")
        let swimTime = document.getElementById("swim-time")
        let swimItself = document.getElementById("swim-itself")